numGraphs = [1, 1, 2, 4, 11, 34, 156, 1044, 12346, 274668, 12005168, 1018997864, 165091172592, 50502031367952, 29054155657235488, 31426485969804308768, 64001015704527557894928, 245935864153532932683719776, 1787577725145611700547878190848, 24637809253125004524383007491432768,645490122795799841856164638490742749440, 32220272899808983433502244253755283616097664, 3070846483094144300637568517187105410586657814272, 559946939699792080597976380819462179812276348458981632, 195704906302078447922174862416726256004122075267063365754368,131331393569895519432161548405816890146389214706146483380458576384,169487618400693135671278778610295749756246061427513800357039083537927168,421260006519643885757174107650953992882782878952295704539600450662355704738816,2019295999678571395728328980890810345860807065053566265347514137546665672316696821760,18691352722478956041683441055221773100906878077027397169675907651818104181986752359177684992,334494316309257669249439569928080028956631479935393064329967834887217734534880582749030521599504384,11585815044205812673379511928863764381265040141261061227725971383046167307510698791401041768792169368940544,777510571865055903406188374366190476598442307924741916354899631006385898637671205231827093391614863192904415807488,101193386573463039354269401142741027463145963826790815082084909468028166503553807396859190074836698829732761747606799118336,25566013871397723851094108820013106182843555852275358804907199250742354688175618766408178934854794054153633107026075263960686854144,];
temp = (0 : (size(numGraphs, 2) -1));
numMats = 2 .^ ((temp .* temp - temp)/2);

matrixRepresentationsPerGraph = numMats ./ numGraphs;
maxRepresentationsPerGraph = factorial(temp);

proportionOfPotential = matrixRepresentationsPerGraph ./ maxRepresentationsPerGraph;

proportionOfPotential = proportionOfPotential .^ -1;

logOffFromOne = log(abs(1 - proportionOfPotential));

% CREATEFIGURE(TEMP1, PROPORTIONOFPOTENTIAL1, DIFF1)
%  TEMP1:  vector of x data
%  PROPORTIONOFPOTENTIAL1:  vector of y data
%  DIFF1:  vector of y data

%  Auto-generated by MATLAB on 27-Mar-2016 12:09:50

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(1,2,1,'Parent',figure1);
hold(subplot1,'on');

% Create plot
plot(temp,proportionOfPotential,'Parent',subplot1,...
    'DisplayName','Representation Proportion',...
    'MarkerFaceColor',[0 0 1],...
    'Marker','o',...
    'LineStyle','--',...
    'Color',[0 0 1]);

% Create xlabel
xlabel('N (Number of Vertices)');

% Create ylabel
ylabel('Matrix Representations / (nGraphs in G_{alg} * N!)');

% Create title
title('Most Graphs Have Only the Trivial Automorphism');

% Uncomment the following line to preserve the X-limits of the axes
 xlim(subplot1,[0 34]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(subplot1,[0.2 1]);
box(subplot1,'on');
% Set the remaining axes properties
set(subplot1,'FontSize',16);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,...
    'Position',[0.257630161579893 0.266075388026608 0.189856373429085 0.0421286031042128]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(temp,logOffFromOne,'Parent',axes1,'DisplayName','Log(1 - Rep. Prop.)',...
    'MarkerFaceColor',[1 0 0],...
    'Marker','o',...
    'LineStyle','--',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('N (Number of Vertices)');

% Create ylabel
ylabel('Log(1 - Representation Proportion)');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'OuterPosition',...
    [0.534263458060926 0 0.409653637501739 1]);
% Create legend
legend2 = legend(axes1,'show');
set(legend2,...
    'Position',[0.610861759425495 0.272727272727273 0.149461400359066 0.0421286031042128]);

fig = gcf;
fig.PaperUnits = 'inches';
fig.PaperPosition = [0 0 12 6];
%print('visualization/numGraphsAndPaths','-dpng','-r0');
%close;
